Add score integration test to standard token & standard crowdsale
icon-project/samples pull request #4
Opened 2018-11-14 06:15 UTC by eunsoo-icon

- Add integration test code 
 - Test code requires tbears package

2018-11-14 12:00 UTC, sojinkim-icon commented
Sorry, I was not aware of this pull request and changed the folder structure. This PR is not mergeable. Would you please resolve the conflict and send another pr ?

2018-11-14 12:00 UTC, sink772 requested changes
Sojin just renamed the directory structures, so you need to modify your codes accordingly.

2018-11-15 00:40 UTC, eunsoo-icon commented
I rebased and modified source codes. Please review again.

2018-11-15 11:23 UTC, sink772 approved these changes

2018-11-15 11:24 UTC, merged